# GitHub Action for PHP Basic Firewall
name: Testing PHP Basic Firewall
on: [ push, pull_request ]
jobs:
    build:
        strategy:
            matrix:
                operating-system: [ ubuntu-latest, windows-latest, macos-latest ]
                php-versions: [ '5.4', '5.5', '5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0' ]
        runs-on: ${{ matrix.operating-system }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Setup PHP, with composer and extensions
                uses: shivammathur/setup-php@v2 # From https://github.com/shivammathur/setup-php
                with:
                    php-version: ${{ matrix.php-versions }}
                    extensions: mbstring, intl, curl, dom, pdo, json, session, sockets, openssl
                    coverage: xdebug #optional
            -   name: Get composer cache directory
                id: composercache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"
            -   name: Cache composer dependencies
                uses: actions/cache@v2
                with:
                    path: ${{ steps.composercache.outputs.dir }}
                    # Use composer.json for key, if composer.lock is not committed.
                    # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-composer-
            -   name: Install dependencies
                run: composer install --no-progress --prefer-dist --optimize-autoloader
            -   name: Check PHP Extension
                run: php ./test/check.php
            -   name: Start PHP Basic Firewall
                run: php ./test/firewall.php